Super gross hack to make configure match

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -422,10 +422,14 @@ qemu_private_xts="yes"
 auth_pam=""
 vte=""
 virglrenderer=""
-tpm=""
-libssh=""
+tpm="yes"
+libssh2=""
+vhdx=""
+quorum="no"
+pcap="no"
+pcap_create="no"
+bpf="no"
 live_block_migration="yes"
-numa=""
 tcmalloc="no"
 jemalloc="no"
 replication="yes"
@@ -1080,6 +1084,10 @@ for opt do
   --disable-vnc-png) vnc_png="disabled"
   ;;
   --enable-vnc-png) vnc_png="enabled"
+  ;;
+  --enable-pcap) pcap="yes"
+  ;;
+  --disable-pcap) pcap="no"
   ;;
   --disable-slirp) slirp="disabled"
   ;;
@@ -1790,6 +1798,7 @@ disabled with --disable-FEATURE, default is enabled if available:
   virtfs          VirtFS
   virtiofsd       build virtiofs daemon (virtiofsd)
   libudev         Use libudev to enumerate host devices
+  pcap            pcap support
   mpath           Multipath persistent reservation passthrough
   xen             xen backend driver support
   xen-pci-passthrough    PCI passthrough support for Xen
@@ -3298,6 +3307,50 @@ EOF
 fi
 
 ##########################################
+# pcap probe
+if test "$pcap" = "yes" -a "$pcap" != "no"; then
+  cat > $TMPC << EOF
+#include <pcap.h>
+int main(void) { return (pcap_lib_version() == (char *)0 ? 1 : 0); }
+EOF
+  if test "$mingw32" = "no" ; then
+    libpcap=-lpcap
+  else
+    libpcap=-lwpcap
+  fi
+  if compile_prog "" "$libpcap" ; then
+    :
+  else
+    echo
+    echo "Error: Could not find pcap"
+    echo "Make sure to have the pcap libs and headers installed."
+    echo
+    exit 1
+  fi
+  cat > $TMPC << EOF
+#include <pcap.h>
+int main(void)
+{
+  char errbuf[PCAP_ERRBUF_SIZE];
+  return (pcap_create("foo", errbuf) == (pcap_t *)0 ? 1 : 0);
+}
+EOF
+  if compile_prog "" "$libpcap" ; then
+    pcap_create="yes"
+  fi
+  cat > $TMPC << EOF
+#define PCAP_DONT_INCLUDE_PCAP_BPF_H
+#include <pcap.h>
+#include <net/bpf.h>
+int main(void) { return (BPF_MAJOR_VERSION); }
+EOF
+  if compile_prog ; then
+    bpf="yes"
+  fi
+  libs_softmmu="$libpcap $libs_softmmu"
+fi # test "$pcap"
+
+##########################################
 # vde libraries probe
 if test "$vde" != "no" ; then
   vde_libs="-lvdeplug"
@@ -4584,6 +4637,17 @@ fi
 
 # check for libusb
 if test "$libusb" != "no" ; then
+    cat > $TMPC << EOF
+#include <libusb.h>
+
+int main(void) { return libusb_get_port_path(NULL, NULL, NULL, 0); }
+EOF
+    if compile_prog "-Werror" "-lusb -pthread" ; then
+        libusb="yes"
+        libusb_cflags=""
+        libusb_libs=-lusb
+        libs_softmmu="$libs_softmmu $libusb_libs"
+    else
     if $pkg_config --atleast-version=1.0.13 libusb-1.0; then
         libusb="yes"
         libusb_cflags=$($pkg_config --cflags libusb-1.0)
@@ -4593,6 +4657,7 @@ if test "$libusb" != "no" ; then
             feature_not_found "libusb" "Install libusb devel >= 1.0.13"
         fi
         libusb="no"
+    fi
     fi
 fi
 
@@ -6052,6 +6117,15 @@ if test "$want_tools" = "yes" ; then
 fi
 if test "$guest_agent" = "yes" ; then
   echo "CONFIG_GUEST_AGENT=y" >> $config_host_mak
+fi
+if test "$pcap" = "yes" ; then
+  echo "CONFIG_PCAP=y" >> $config_host_mak
+  if test "$pcap_create" = "yes" ; then
+    echo "CONFIG_PCAP_CREATE=y" >> $config_host_mak
+  fi
+  if test "$bpf" = "yes" ; then
+    echo "CONFIG_BPF=y" >> $config_host_mak
+  fi
 fi
 echo "CONFIG_SMBD_COMMAND=\"$smbd\"" >> $config_host_mak
 if test "$vde" = "yes" ; then
